namespace_name: internal-monitoring
cluster_name: home
tls_enabled: false

# use for external routing
enable_remote_otlp_exporter: false
otlp_http_endpoint: https://otel-http.neryolab.com

enable_grafana_cloud_exporter: false
# configs are located in group_vars/all

# use for internal routing
mimir_endpoint: http://mimir-service.robsgbl0.svc.cluster.local:9009/api/v1/push
loki_endpoint: http://loki-service.robsgbl0.svc.cluster.local:3100/loki/api/v1/push
