alloy_image: grafana/alloy:latest

prom_remote_write:
  url: "http://prometheus:9090/api/v1/write"
  #basic_auth:
  #  username: "prom_user"
  #  password: "prom_pass"
  disable_tls: false

loki:
  url: "http://loki:3100/loki/api/v1/push"
  basic_auth:
    username: "loki_user"
    password: "loki_pass"
  disable_tls: false