all:
  children:
    kubernetes:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: /Users/hugues/.pyenv/versions/3.13.3/bin/python3
    
    remote:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: /Users/hugues/.pyenv/versions/3.13.3/bin/python3
        # pg-server:
          # ansible_host: 192.168.1.24
          # ansible_user: "{{ ansible_user | default('ansible') }}"
          # ansible_ssh_private_key_file: "{{ ansible_ssh_key | default('~/.ssh/id_rsa') }}"